### ISSUE TITLE
Crash InAppMessaging

### ISSUE THREAD

**Issue by sgueniot-ua** [wonderpush/wonderpush-android-sdk#10]
Hello, 
We are sometimes seeing crash reports with the sdk 4.3.1 (about 800 in the last 90 days). I updated it to 4.3.5 but nothing in the changelog mentions these issues, so I assume they are still present. Can we get help to fix this? The stacktrace does not give us a point of entry into our code, it is the wonderpush code that seems to be crashing. 
this is the  first one : 
```
Fatal Exception: java.lang.StackOverflowError: stack size 8188KB
       at com.wonderpush.sdk.inappmessaging.display.internal.MediaLoader$1.onError(MediaLoader.java:35)
       at com.wonderpush.sdk.inappmessaging.display.internal.MediaLoader$1.onError(MediaLoader.java:35)
       at com.wonderpush.sdk.inappmessaging.display.internal.MediaLoader$1.onError(MediaLoader.java:35)
       at com.wonderpush.sdk.inappmessaging.display.internal.MediaLoader$1.onError(MediaLoader.java:35)
       at com.wonderpush.sdk.inappmessaging.display.internal.MediaLoader$1.onError(MediaLoader.java:35)
       at com.wonderpush.sdk.inappmessaging.display.internal.MediaLoader$1.onError(MediaLoader.java:35)
       at com.wonderpush.sdk.inappmessaging.display.internal.MediaLoader$1.onError(MediaLoader.java:35)
       at com.wonderpush.sdk.inappmessaging.display.internal.MediaLoader$1.onError(MediaLoader.java:35)
       at com.wonderpush.sdk.inappmessaging.display.internal.MediaLoader$1.onError(MediaLoader.java:35)
       at com.wonderpush.sdk.inappmessaging.display.internal.MediaLoader$1.onError(MediaLoader.java:35)
       at com.squareup.picasso.ImageViewAction.error(ImageViewAction.java:72)
       at com.squareup.picasso.Picasso.deliverAction(Picasso.java:581)
       at com.squareup.picasso.Picasso.complete(Picasso.java:528)
       at com.squareup.picasso.Picasso$1.handleMessage(Picasso.java:122)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8762)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```
The second One : 
```
Fatal Exception: android.view.WindowManager$BadTokenException: Unable to add window -- token null is not valid; is your activity running?
       at android.view.ViewRootImpl.setView(ViewRootImpl.java:1764)
       at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:567)
       at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:148)
       at com.wonderpush.sdk.inappmessaging.display.internal.IamWindowManager.show(IamWindowManager.java:64)
       at com.wonderpush.sdk.inappmessaging.display.InAppMessagingDisplay$8.run(InAppMessagingDisplay.java:500)
       at android.app.Activity.runOnUiThread(Activity.java:7494)
       at com.wonderpush.sdk.inappmessaging.display.InAppMessagingDisplay.lambda$inflateBinding$2(InAppMessagingDisplay.java:496)
       at com.wonderpush.sdk.inappmessaging.display.internal.MediaLoader$1.onSuccess(MediaLoader.java:30)
       at com.squareup.picasso.ImageViewAction.complete(ImageViewAction.java:52)
       at com.squareup.picasso.Picasso.deliverAction(Picasso.java:576)
       at com.squareup.picasso.Picasso.complete(Picasso.java:528)
       at com.squareup.picasso.Picasso$1.handleMessage(Picasso.java:122)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8757)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```
Thank you in advance.

**Comment by ofavre** [comment]
Hi,

The first error is fixed in 27e7e19e1f3e1b7d973dd64a7ca7fd69985c533e released in v4.3.2 and the second is fixed in ba2b9a10e83d9316d33f9682ec03acadc3c0199d released in v4.4.1.
